# Generated by Django 3.0 on 2019-12-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='band_or_not',
            new_name='band',
        ),
    ]
