# Generated by Django 3.0 on 2019-12-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdb', '0002_auto_20191217_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='selled',
            field=models.PositiveIntegerField(default=1400000),
            preserve_default=False,
        ),
    ]
