# Generated by Django 3.0 on 2019-12-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdb', '0003_song_selled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='singers',
            field=models.ManyToManyField(blank=True, related_name='songs', to='songdb.Person'),
        ),
    ]
