# Generated by Django 3.0 on 2019-12-21 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songdb', '0004_auto_20191218_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songdb.Country'),
        ),
    ]
