# Generated by Django 3.0 on 2019-12-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdb', '0005_auto_20191221_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='alias',
            field=models.TextField(default='_'),
            preserve_default=False,
        ),
    ]
