# Generated by Django 3.0 on 2019-12-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdb', '0006_auto_20191221_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='alias',
            field=models.TextField(null=True),
        ),
    ]
